// ==================================================
// PHASE 8 — BAN MANAGEMENT MODULE
// ==================================================
// Same shape as vipApproval.js / diamondSeller.js: the REQUEST side
// (Submit -> Review -> Approve/Reject -> Reopen, History, Comments, Audit
// Log, Country Isolation, Permission Checks, Owner Override, Search/
// Pagination/Filters) is 100% generated by the shared approvalEngine.js —
// no second state machine written. Everything that happens to an
// already-approved BAN (not a pending request) — Suspend/Restore/Reopen,
// the Appeal sub-flow, and the dashboard /summary — is hand-written on a
// second registry (bans.json, keyed by banId), reusing the exact same
// building blocks (rbac.hasPermission, actorCanAccessCountry,
// rbac.logAction, isOwner override) so the security model stays
// identical even though the route isn't generated by the engine.
//
// RBAC (per Phase 8 instruction):
//   Owner / Global Super Admin -> full access (view/submit/review/
//     approve/appeal-review/appeal-decide), any country.
//   Country Manager            -> view/review/appeal-review, own
//     country only (enforced by actorCanAccessCountry, same as every
//     other approval domain).
//   Admin                      -> submit/view only.
//   Moderator                  -> no ban permission at all (hidden).
// New permissions (ban:view/submit/review/approve/appeal-review/
// appeal-decide) were added additively to rbac.js's PERMISSIONS list and
// role defaults — nothing existing in rbac.js was edited or removed.
//
// Device/IP ban scope note (honesty, same spirit as diamondSeller.js's
// KYC-document scope note): banType "device"/"ip" is fully supported as
// a record (stored, filterable, shown in the UI, included in the
// /summary count) but this module does NOT wire real-time login-time
// device/IP blocking into server.js's socket/login handlers — that would
// mean editing server.js's existing auth logic, which the instruction
// explicitly forbids touching. Only the existing user-level
// `user.banned` flag (already enforced at login) is applied for every
// ban type, including device/ip. Flagged in RBAC_MIGRATION_NOTES.md as a
// scope limitation to revisit if real device/IP-level login blocking is
// wanted later.
//
// This file is additive and self-contained (same pattern as rbac.js /
// approvalEngine.js / vipApproval.js) — it does not import or modify any
// other file.

const path = require("path");
const crypto = require("crypto");
const { createApprovalWorkflow } = require("./approvalEngine.js");

const BAN_TYPES = ["temporary", "permanent", "device", "ip"];
const MIN_DURATION_DAYS = 1;
const MAX_DURATION_DAYS = 3650; // ~10 years, sane cap for "temporary"

function clampDays(n) {
    const v = Math.floor(Number(n));
    if (!Number.isFinite(v)) return null;
    if (v < MIN_DURATION_DAYS || v > MAX_DURATION_DAYS) return null;
    return v;
}

function initBanManagement(deps) {
    const {
        app, DATA_FOLDER, safeRead, safeWrite,
        findUserByUserId, saveUsers, syncProfileToRoom,
        io, socketsByUserId, emitToUser,
        rbac, requireAdmin, requirePermission,
        actorCanAccessCountry, countryDeniedResponse, reqUserAgent
    } = deps;

    const engineDeps = { app, DATA_FOLDER, safeRead, safeWrite, rbac, requireAdmin, requirePermission, actorCanAccessCountry, countryDeniedResponse, reqUserAgent };

    function isOwner(actor) { return actor && actor.role === rbac.ROLES.OWNER; }
    function actorTag(req) { return { id: req.adminAccount.id, username: req.adminAccount.username }; }

    // GAP #1 — cross-instance-safe via emitToUser()
    function notifyUser(userId, event, extra) {
        emitToUser(userId, "ban-notification", Object.assign({ event }, extra || {}));
    }

    function syncUserProfile(userId) {
        if (typeof syncProfileToRoom === "function") { try { syncProfileToRoom(userId); } catch (_) { /* room sync is best-effort */ } }
    }

    // --------------------------------------------------
    // Ban registry — separate from the request store the engine manages.
    // A ban REQUEST becoming "approved" is what CREATES a row here.
    // --------------------------------------------------
    const BANS_FILE = path.join(DATA_FOLDER, "bans.json");
    let bans = safeRead(BANS_FILE, {});
    function saveBans() { safeWrite(BANS_FILE, bans); }

    function pushBanHistory(b, entry) {
        if (!Array.isArray(b.history)) b.history = [];
        b.history.push(Object.assign({ at: new Date().toISOString() }, entry));
    }

    function snapshotBan(b) { return b ? Object.assign({}, b, { history: (b.history || []).slice() }) : null; }

    function applyBanToUser(b) {
        const found = findUserByUserId(b.userId);
        if (!found) return;
        found.user.banned = true;
        saveUsers();
        syncUserProfile(b.userId);
    }

    function applyRestoreToUser(userId) {
        const found = findUserByUserId(userId);
        if (!found) return;
        found.user.banned = false;
        saveUsers();
        syncUserProfile(userId);
    }

    // ==================================================
    // 1. BAN REQUEST workflow (Submit -> Review -> Approve/Reject ->
    //    Reopen), fully generated by approvalEngine.js. Scoped by the
    //    TARGET USER's country (not the submitting admin's) — same
    //    convention as VIP/Recharge/Withdraw — since this action changes
    //    that user's account state.
    // ==================================================
    const request = createApprovalWorkflow({
        deps: engineDeps,
        domain: "ban",
        fileName: "ban_requests.json",
        basePath: "/api/admin/bans/requests",
        idPrefix: "banq_",
        permissions: { view: "ban:view", submit: "ban:submit", review: "ban:review", approve: "ban:approve" },
        extraSearchFields: ["banType", "reason", "targetUserName"],
        validateSubmit(body) {
            const found = findUserByUserId(body.targetUserId);
            if (!found) return { ok: false, message: "Provide a valid Target User ID (must be an existing user)" };
            if (found.user.banned) return { ok: false, message: "This user is already banned" };

            const banType = BAN_TYPES.includes(body.banType) ? body.banType : null;
            if (!banType) return { ok: false, message: "Select a valid Ban Type (" + BAN_TYPES.join("/") + ")" };

            const reason = (body.reason || "").trim();
            if (!reason) return { ok: false, message: "Provide a Ban Reason" };

            let durationDays = null;
            if (banType !== "permanent") {
                durationDays = clampDays(body.durationDays);
                if (!durationDays) return { ok: false, message: `Duration ${MIN_DURATION_DAYS}-${MAX_DURATION_DAYS} days` };
            }

            const deviceId = banType === "device" ? (body.deviceId || "").trim() || null : null;
            const ipAddress = banType === "ip" ? (body.ipAddress || "").trim() || null : null;
            if (banType === "device" && !deviceId) return { ok: false, message: "Provide a Device ID for Device Ban" };
            if (banType === "ip" && !ipAddress) return { ok: false, message: "Provide an IP Address for IP Ban" };

            return {
                ok: true,
                userId: body.targetUserId,
                countryId: found.user.countryId || "OTHERS",
                data: { domain: "ban", banType, reason, durationDays, deviceId, ipAddress, targetUserName: found.user.name || null }
            };
        },
        onApprove(record, req) {
            const found = findUserByUserId(record.userId);
            if (!found) return { ok: false, message: "User no longer exists" };
            if (found.user.banned) return { ok: false, message: "This user is already banned" };

            const banId = "ban_" + Date.now().toString(36) + "_" + crypto.randomBytes(4).toString("hex");
            const now = new Date().toISOString();
            const expiryAt = record.durationDays ? new Date(Date.now() + record.durationDays * 24 * 60 * 60 * 1000).toISOString() : null;
            const ban = {
                banId,
                userId: record.userId,
                userName: record.targetUserName || found.user.name || null,
                countryId: record.countryId,
                banType: record.banType,
                reason: record.reason,
                durationDays: record.durationDays,
                deviceId: record.deviceId,
                ipAddress: record.ipAddress,
                status: "active", // active -> expired | restored
                assignedAdmin: actorTag(req),
                viaRequestId: record.requestId,
                appealStatus: null, // null -> pending -> under_review -> restored | rejected
                appealHistory: [],
                history: [],
                createdAt: now,
                updatedAt: now,
                expiryAt
            };
            pushBanHistory(ban, { type: "ban-applied", by: actorTag(req), banType: ban.banType, reason: ban.reason, expiryAt });
            bans[banId] = ban;
            saveBans();
            applyBanToUser(ban);

            notifyUser(record.userId, "banned", { banId, banType: ban.banType, reason: ban.reason, expiryAt });
            return { ok: true, extra: { banId } };
        },
        onNotify(record, event) {
            // GAP #1 — cross-instance-safe via emitToUser()
            emitToUser(record.userId, "approval-notification", {
                domain: "ban", requestId: record.requestId, status: record.status, event,
                note: record.decisionNote || record.reviewNote || null
            });
        }
    });

    // ==================================================
    // 2. SUMMARY — dashboard cards. ban:view.
    // ==================================================
    app.get("/api/admin/bans/summary", requireAdmin, requirePermission("ban:view"), (req, res) => {
        const list = Object.values(bans).filter((b) => actorCanAccessCountry(req.adminAccount, b.countryId));
        const now = Date.now();
        const isExpired = (b) => b.expiryAt && new Date(b.expiryAt).getTime() <= now;
        res.json({
            success: true,
            summary: {
                activeBans: list.filter((b) => b.status === "active" && !isExpired(b)).length,
                temporaryBans: list.filter((b) => b.banType === "temporary").length,
                permanentBans: list.filter((b) => b.banType === "permanent").length,
                deviceIpBans: list.filter((b) => b.banType === "device" || b.banType === "ip").length,
                pendingAppeals: list.filter((b) => b.appealStatus === "pending" || b.appealStatus === "under_review").length,
                restored: list.filter((b) => b.status === "restored").length,
                rejectedAppeals: list.filter((b) => b.appealStatus === "rejected").length
            }
        });
    });

    // ==================================================
    // 3. BAN LIST + DETAILS — search / filter / pagination on the ban
    //    registry (not the request queue). ban:view.
    // ==================================================
    app.get("/api/admin/bans", requireAdmin, requirePermission("ban:view"), (req, res) => {
        let list = Object.values(bans).filter((b) => actorCanAccessCountry(req.adminAccount, b.countryId));
        if (req.query.countryId) list = list.filter((b) => b.countryId === req.query.countryId);
        if (req.query.banType) list = list.filter((b) => b.banType === req.query.banType);
        if (req.query.status) list = list.filter((b) => b.status === req.query.status);
        if (req.query.reason) list = list.filter((b) => (b.reason || "").toLowerCase().includes(String(req.query.reason).toLowerCase()));
        if (req.query.dateFrom) list = list.filter((b) => new Date(b.createdAt) >= new Date(req.query.dateFrom));
        if (req.query.dateTo) list = list.filter((b) => new Date(b.createdAt) <= new Date(req.query.dateTo));
        if (req.query.q) {
            const q = String(req.query.q).toLowerCase();
            list = list.filter((b) => ["banId", "userId", "userName", "reason"].some((f) => String(b[f] || "").toLowerCase().includes(q)));
        }
        const sortField = req.query.sortBy && Object.prototype.hasOwnProperty.call(list[0] || {}, req.query.sortBy) ? req.query.sortBy : "updatedAt";
        const sortDir = req.query.sortDir === "asc" ? 1 : -1;
        list = list.slice().sort((a, b) => (new Date(a[sortField] || 0) - new Date(b[sortField] || 0)) * sortDir);
        const total = list.length;
        const pageSize = Math.min(Number(req.query.pageSize) || 50, 200);
        const page = Math.max(Number(req.query.page) || 1, 1);
        const start = (page - 1) * pageSize;
        res.json({ success: true, bans: list.slice(start, start + pageSize), total, page, pageSize });
    });

    app.get("/api/admin/bans/:banId", requireAdmin, requirePermission("ban:view"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        res.json({ success: true, ban: b });
    });

    // ==================================================
    // 4. BAN ACTIONS — Reopen / Restore / Comment on an already-active
    //    ban record. ban:approve (Owner override applies via isOwner()).
    // ==================================================
    app.post("/api/admin/bans/:banId/restore", requireAdmin, requirePermission("ban:approve"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (b.status !== "active" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Only an 'active' ban can be restored (current status: " + b.status + ")" });
        }
        const by = actorTag(req);
        b.status = "restored";
        b.updatedAt = new Date().toISOString();
        pushBanHistory(b, { type: "restore", by, note: req.body.note || null });
        saveBans();
        applyRestoreToUser(b.userId);
        rbac.logAction({ admin: req.adminAccount, action: "ban-restore", module: "ban", targetType: "ban", targetId: b.banId, after: snapshotBan(b), ip: req.ip, userAgent: reqUserAgent(req) });
        notifyUser(b.userId, "restored", { banId: b.banId });
        res.json({ success: true, ban: b });
    });

    app.post("/api/admin/bans/:banId/reopen", requireAdmin, requirePermission("ban:approve"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (b.status !== "restored" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Only a 'restored' ban can be reopened (current status: " + b.status + ")" });
        }
        const found = findUserByUserId(b.userId);
        if (found && found.user.banned) return res.json({ success: false, message: "This user is already banned" });
        const by = actorTag(req);
        b.status = "active";
        b.updatedAt = new Date().toISOString();
        pushBanHistory(b, { type: "reopen", by, note: req.body.note || null });
        saveBans();
        applyBanToUser(b);
        rbac.logAction({ admin: req.adminAccount, action: "ban-reopen", module: "ban", targetType: "ban", targetId: b.banId, after: snapshotBan(b), ip: req.ip, userAgent: reqUserAgent(req) });
        notifyUser(b.userId, "reopened", { banId: b.banId });
        res.json({ success: true, ban: b });
    });

    app.post("/api/admin/bans/:banId/comment", requireAdmin, requirePermission("ban:view"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        const text = (req.body.text || "").trim();
        if (!text) return res.json({ success: false, message: "Provide comment text" });
        const by = actorTag(req);
        pushBanHistory(b, { type: "comment", by, note: text.slice(0, 500) });
        b.updatedAt = new Date().toISOString();
        saveBans();
        rbac.logAction({ admin: req.adminAccount, action: "ban-comment", module: "ban", targetType: "ban", targetId: b.banId, ip: req.ip, userAgent: reqUserAgent(req) });
        res.json({ success: true, ban: b });
    });

    // ==================================================
    // 5. APPEAL MANAGEMENT — sub-flow on the ban record itself.
    //    submit: ban:view (any admin who can see the ban can log an
    //    appeal on the user's behalf); review: ban:appeal-review;
    //    decide (restore/reject): ban:appeal-decide.
    // ==================================================
    app.post("/api/admin/bans/:banId/appeal", requireAdmin, requirePermission("ban:view"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (b.status !== "active") return res.json({ success: false, message: "An appeal can only be filed on an 'active' ban" });
        if (b.appealStatus === "pending" || b.appealStatus === "under_review") {
            return res.json({ success: false, message: "An appeal is already in progress for this ban" });
        }
        const by = actorTag(req);
        b.appealStatus = "pending";
        b.updatedAt = new Date().toISOString();
        b.appealHistory.push({ at: new Date().toISOString(), type: "appeal-submit", by, note: req.body.note || null });
        pushBanHistory(b, { type: "appeal-submit", by, note: req.body.note || null });
        saveBans();
        rbac.logAction({ admin: req.adminAccount, action: "ban-appeal-submit", module: "ban", targetType: "ban", targetId: b.banId, ip: req.ip, userAgent: reqUserAgent(req) });
        res.json({ success: true, ban: b });
    });

    app.post("/api/admin/bans/:banId/appeal/review", requireAdmin, requirePermission("ban:appeal-review"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (b.appealStatus !== "pending" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Only a 'pending' appeal can be reviewed (current: " + b.appealStatus + ")" });
        }
        const by = actorTag(req);
        b.appealStatus = "under_review";
        b.updatedAt = new Date().toISOString();
        b.appealHistory.push({ at: new Date().toISOString(), type: "appeal-review", by, note: req.body.note || null });
        pushBanHistory(b, { type: "appeal-review", by, note: req.body.note || null });
        saveBans();
        rbac.logAction({ admin: req.adminAccount, action: "ban-appeal-review", module: "ban", targetType: "ban", targetId: b.banId, ip: req.ip, userAgent: reqUserAgent(req) });
        res.json({ success: true, ban: b });
    });

    app.post("/api/admin/bans/:banId/appeal/restore", requireAdmin, requirePermission("ban:appeal-decide"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (!["pending", "under_review"].includes(b.appealStatus) && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Restore is only allowed on a 'pending' or 'under_review' appeal" });
        }
        const by = actorTag(req);
        b.appealStatus = "restored";
        b.status = "restored";
        b.updatedAt = new Date().toISOString();
        b.appealHistory.push({ at: new Date().toISOString(), type: "appeal-restore", by, note: req.body.note || null });
        pushBanHistory(b, { type: "appeal-restore", by, note: req.body.note || null });
        saveBans();
        applyRestoreToUser(b.userId);
        rbac.logAction({ admin: req.adminAccount, action: "ban-appeal-restore", module: "ban", targetType: "ban", targetId: b.banId, after: snapshotBan(b), ip: req.ip, userAgent: reqUserAgent(req) });
        notifyUser(b.userId, "appeal-restored", { banId: b.banId });
        res.json({ success: true, ban: b });
    });

    app.post("/api/admin/bans/:banId/appeal/reject", requireAdmin, requirePermission("ban:appeal-decide"), (req, res) => {
        const b = bans[req.params.banId];
        if (!b) return res.json({ success: false, message: "Ban record not found" });
        if (!actorCanAccessCountry(req.adminAccount, b.countryId)) return countryDeniedResponse(res);
        if (!["pending", "under_review"].includes(b.appealStatus) && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Reject is only allowed on a 'pending' or 'under_review' appeal" });
        }
        const by = actorTag(req);
        b.appealStatus = "rejected";
        b.updatedAt = new Date().toISOString();
        b.appealHistory.push({ at: new Date().toISOString(), type: "appeal-reject", by, note: req.body.note || req.body.reason || null });
        pushBanHistory(b, { type: "appeal-reject", by, note: req.body.note || req.body.reason || null });
        saveBans();
        rbac.logAction({ admin: req.adminAccount, action: "ban-appeal-reject", module: "ban", targetType: "ban", targetId: b.banId, after: snapshotBan(b), ip: req.ip, userAgent: reqUserAgent(req) });
        notifyUser(b.userId, "appeal-rejected", { banId: b.banId });
        res.json({ success: true, ban: b });
    });

    return { bans, saveBans, request };
}

module.exports = { initBanManagement };
