// ==================================================
// PHASE 6 — DIAMOND SELLER MODULE (item 11 of the dev sequence)
// ==================================================
// Registration/KYC approval is built on the shared approvalEngine.js
// (same as Agency/Recharge/Withdraw/Name Effects/Frames/Gifts) — NO
// second engine written, per instruction. approvalEngine.js gives this
// module, for free, on the request itself: Submit -> Review -> Approve/
// Reject -> Reopen, Approval History/Timeline, Comments, Audit Log,
// Country Isolation, Permission Checks, Owner Override, Search/
// Pagination/Filters on the request list.
//
// Everything the request workflow can't express on its own — because it
// happens to an already-approved SELLER, not to a pending REQUEST — is
// added here as a small set of hand-written routes on a second store
// (diamond_sellers.json, keyed by sellerId): Suspend/Restore, Commission
// Settings, Commission History, and the Wallet-Integrated "sale" action
// that actually moves diamonds/coins. These routes reuse the exact same
// building blocks (rbac.hasPermission, actorCanAccessCountry, rbac.logAction,
// isOwner override) so the security model stays identical even though the
// route isn't generated by the engine.
//
// Wallet Integration note (honesty): this module does NOT invent a new
// ledger. A "sale" credits the buyer's diamonds and the seller's coins
// through the exact same primitives Recharge/Withdraw already use
// (findUserByUserId, saveUsers, logTransaction, pushWalletUpdate,
// levelFromCoins) — so existing wallet logic/balance-history keeps working
// unchanged; this only adds a new *caller* of it.
//
// Document Upload (honesty): KYC documents are real multipart uploads
// (own multer instance, own folder — created by this module itself, not
// by editing server.js's folder-setup block) but are served through a
// permission-gated route (diamond-seller:view) rather than a public
// express.static mount, since these are identity documents and the rest
// of this app's uploaded-asset folders (frames/gift images/etc.) are
// intentionally public. Fine-grained per-country access on the raw file
// itself is NOT enforced (any admin holding diamond-seller:view can fetch
// any seller's document by URL) — flagged in RBAC_MIGRATION_NOTES.md as a
// scope limitation to revisit if this ever needs per-country document
// isolation.
//
// rbac.js is NOT touched by this module — every permission it needs
// (diamond-seller:view/submit/review/approve/suspend) and every default
// role assignment were already reserved in the Phase 6 item 2 step
// specifically so later modules like this one wouldn't need an RBAC
// migration. Confirmed unchanged here, as instructed.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const multer = require("multer");
const { createApprovalWorkflow } = require("./approvalEngine.js");

const KYC_ID_TYPES = ["nid", "passport", "driving_license"];
const DEFAULT_COMMISSION_RATE = 5;   // percent
const MIN_COMMISSION_RATE = 0;
const MAX_COMMISSION_RATE = 30;      // sane cap so a fat-fingered rate can't drain a sale

function clampRate(n, fallback) {
    const v = Number(n);
    if (!Number.isFinite(v)) return fallback;
    return Math.min(MAX_COMMISSION_RATE, Math.max(MIN_COMMISSION_RATE, v));
}

function initDiamondSeller(deps) {
    const {
        app, DATA_FOLDER, safeRead, safeWrite,
        findUserByUserId, saveUsers, logTransaction, pushWalletUpdate, levelFromCoins,
        io, socketsByUserId, emitToUser,
        rbac, requireAdmin, requirePermission,
        actorCanAccessCountry, countryDeniedResponse, reqUserAgent
    } = deps;
    // AUDIT FIX (Phase 13, wallet/economy audit, 2026-07-28): route this
    // module's two credit sites (buyer diamonds, seller commission coins)
    // through the same ceiling/overflow guards used everywhere else in the
    // economy. Falls back to a local equivalent if wired up without these
    // deps, so the guard can never silently no-op.
    const clampCoins = typeof deps.clampCoinBalance === "function" ? deps.clampCoinBalance : (userId, coins) => {
        if (!Number.isFinite(coins) || coins < 0) return 0;
        return Math.min(Math.floor(coins), 100000000000);
    };
    const clampDiamonds = typeof deps.clampDiamondBalance === "function" ? deps.clampDiamondBalance : (userId, diamonds) => {
        if (!Number.isFinite(diamonds) || diamonds < 0) return 0;
        return Math.min(Math.floor(diamonds), 10000000000);
    };

    const engineDeps = { app, DATA_FOLDER, safeRead, safeWrite, rbac, requireAdmin, requirePermission, actorCanAccessCountry, countryDeniedResponse, reqUserAgent };

    function isOwner(actor) { return actor && actor.role === rbac.ROLES.OWNER; }
    function actorTag(req) { return { id: req.adminAccount.id, username: req.adminAccount.username }; }

    // --------------------------------------------------
    // KYC document upload — own multer instance, own folder (created here,
    // not by editing server.js's shared folder-setup block).
    // --------------------------------------------------
    const { resolveUploadsRoot } = require("./perf/dataFolder.js");
    const KYC_DOC_FOLDER = path.join(resolveUploadsRoot(__dirname), "kyc-documents");
    if (!fs.existsSync(KYC_DOC_FOLDER)) fs.mkdirSync(KYC_DOC_FOLDER, { recursive: true });
    const kycStorage = multer.diskStorage({
        destination: (req, file, cb) => cb(null, KYC_DOC_FOLDER),
        filename: (req, file, cb) => cb(null, Date.now() + "-" + crypto.randomBytes(4).toString("hex") + "-" + file.originalname)
    });
    const uploadKycDoc = multer({
        storage: kycStorage,
        limits: { fileSize: 8 * 1024 * 1024 }, // 8MB — plenty for an ID photo/scan/PDF
        fileFilter: (req, file, cb) => {
            const ok = ["image/png", "image/jpeg", "image/webp", "application/pdf"].includes(file.mimetype);
            if (!ok) return cb(new Error("Only PNG/JPEG/WEBP/PDF documents can be uploaded"));
            cb(null, true);
        }
    });

    app.post("/api/admin/diamond-seller/upload-document", requireAdmin, requirePermission("diamond-seller:submit"),
        (req, res, next) => uploadKycDoc.single("document")(req, res, (err) => {
            if (err) return res.status(400).json({ success: false, message: err.message || "Upload failed" });
            next();
        }),
        (req, res) => {
            if (!req.file) return res.json({ success: false, message: "Provide a file" });
            const url = "/api/admin/diamond-seller/document/" + req.file.filename;
            rbac.logAction({
                admin: req.adminAccount, action: "diamond-seller-document-upload", module: "diamond-seller",
                targetType: "kyc-document", targetId: req.file.filename,
                ip: req.ip, userAgent: reqUserAgent(req)
            });
            res.json({ success: true, url, filename: req.file.filename });
        });

    // Permission-gated serving (not a public express.static mount — see
    // scope note above).
    app.get("/api/admin/diamond-seller/document/:filename", requireAdmin, requirePermission("diamond-seller:view"), (req, res) => {
        const safeName = path.basename(req.params.filename); // no path traversal
        const filePath = path.join(KYC_DOC_FOLDER, safeName);
        if (!fs.existsSync(filePath)) return res.status(404).json({ success: false, message: "Document not found" });
        res.sendFile(filePath);
    });

    // --------------------------------------------------
    // Seller registry store — separate from the request store the engine
    // manages. A request becoming "approved" is what CREATES a row here.
    // --------------------------------------------------
    const SELLERS_FILE = path.join(DATA_FOLDER, "diamond_sellers.json");
    let sellers = safeRead(SELLERS_FILE, {});
    function saveSellers() { safeWrite(SELLERS_FILE, sellers); }

    // GAP #1 — cross-instance-safe via emitToUser()
    function notifySeller(seller, event, extra) {
        emitToUser(seller.userId, "diamond-seller-notification", Object.assign({
            sellerId: seller.sellerId, event, status: seller.status, commissionRate: seller.commissionRate
        }, extra || {}));
    }

    // ==================================================
    // 1. REGISTRATION / KYC approval workflow (Submit -> Review ->
    //    Approve/Reject -> Reopen), fully generated by approvalEngine.js.
    // ==================================================
    const registration = createApprovalWorkflow({
        deps: engineDeps,
        domain: "diamond-seller",
        fileName: "diamond_seller_requests.json",
        basePath: "/api/admin/diamond-seller/requests",
        idPrefix: "dsq_",
        permissions: { view: "diamond-seller:view", submit: "diamond-seller:submit", review: "diamond-seller:review", approve: "diamond-seller:approve" },
        extraSearchFields: ["fullName", "kycIdNumber"],
        validateSubmit(body, req) {
            const found = findUserByUserId(body.userId);
            if (!found) return { ok: false, message: "Provide a valid User ID (must be an existing user)" };
            if (found.user.isDiamondSeller) return { ok: false, message: "This user is already a Diamond Seller" };

            const fullName = (body.fullName || "").trim();
            if (!fullName) return { ok: false, message: "Provide full name" };

            const kycIdType = KYC_ID_TYPES.includes(body.kycIdType) ? body.kycIdType : null;
            if (!kycIdType) return { ok: false, message: "Provide a valid KYC ID Type (nid/passport/driving_license)" };

            const kycIdNumber = (body.kycIdNumber || "").trim();
            if (!kycIdNumber || kycIdNumber.length < 4) return { ok: false, message: "Provide a valid KYC ID Number" };

            let documents = body.documents;
            if (typeof documents === "string") { try { documents = JSON.parse(documents); } catch (_) { documents = [documents]; } }
            if (!Array.isArray(documents)) documents = [];
            documents = documents.map((d) => String(d || "").trim()).filter(Boolean).slice(0, 10);
            if (documents.length === 0) return { ok: false, message: "Provide at least one KYC Document upload/URL" };

            // Country Assignment — defaults to the applying user's own
            // country, but a submitter with cross-country access (Global/
            // Country Super Admin) may explicitly assign a different one;
            // actorCanAccessCountry below is still the real enforcement.
            let countryId = (body.countryId || found.user.countryId || "OTHERS").toUpperCase();
            if (!rbac.COUNTRY_IDS.includes(countryId)) countryId = found.user.countryId || "OTHERS";

            const commissionRate = clampRate(body.requestedCommissionRate, DEFAULT_COMMISSION_RATE);

            return {
                ok: true,
                userId: body.userId,
                countryId,
                data: {
                    domain: "diamond-seller",
                    fullName, kycIdType, kycIdNumber, documents,
                    requestedCommissionRate: commissionRate
                }
            };
        },
        onApprove(record, req) {
            const found = findUserByUserId(record.userId);
            if (!found) return { ok: false, message: "User no longer exists" };
            if (found.user.isDiamondSeller) return { ok: false, message: "This user is already a Diamond Seller" };

            const sellerId = "dslr_" + Date.now().toString(36) + "_" + crypto.randomBytes(4).toString("hex");
            const seller = {
                sellerId,
                userId: record.userId,
                countryId: record.countryId,
                fullName: record.fullName,
                kycIdType: record.kycIdType,
                kycIdNumber: record.kycIdNumber,
                documents: record.documents,
                commissionRate: record.requestedCommissionRate,
                status: "active",
                totalDiamondsSold: 0,
                totalCommissionCoins: 0,
                commissionHistory: [],
                viaRequestId: record.requestId,
                approvedBy: actorTag(req),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            };
            sellers[sellerId] = seller;
            saveSellers();

            found.user.isDiamondSeller = true;
            found.user.diamondSellerId = sellerId;
            saveUsers();

            notifySeller(seller, "approved");
            return { ok: true, extra: { sellerId } };
        },
        onNotify(record, event) {
            // GAP #1 — cross-instance-safe via emitToUser()
            emitToUser(record.userId, "approval-notification", {
                domain: "diamond-seller", requestId: record.requestId, status: record.status, event,
                note: record.decisionNote || record.reviewNote || null
            });
        }
    });

    function requireAnyPermission(permsList) { return registration.requireAnyPermission(permsList); }

    // ==================================================
    // 2. SELLER LIST — search / filter / pagination (on the seller
    //    registry, not the request queue).
    // ==================================================
    app.get("/api/admin/diamond-seller/sellers", requireAdmin, requirePermission("diamond-seller:view"), (req, res) => {
        let list = Object.values(sellers).filter((s) => actorCanAccessCountry(req.adminAccount, s.countryId));
        if (req.query.status) list = list.filter((s) => s.status === req.query.status);
        if (req.query.countryId) list = list.filter((s) => s.countryId === req.query.countryId);
        if (req.query.userId) list = list.filter((s) => s.userId === req.query.userId);
        if (req.query.q) {
            const q = String(req.query.q).toLowerCase();
            list = list.filter((s) => [s.sellerId, s.userId, s.fullName, s.kycIdNumber].some((f) => String(f || "").toLowerCase().includes(q)));
        }
        list = list.slice().sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
        const total = list.length;
        const pageSize = Math.min(Number(req.query.pageSize) || 50, 200);
        const page = Math.max(Number(req.query.page) || 1, 1);
        const start = (page - 1) * pageSize;
        res.json({ success: true, sellers: list.slice(start, start + pageSize), total, page, pageSize });
    });

    app.get("/api/admin/diamond-seller/sellers/:sellerId", requireAdmin, requirePermission("diamond-seller:view"), (req, res) => {
        const seller = sellers[req.params.sellerId];
        if (!seller) return res.json({ success: false, message: "Seller not found" });
        if (!actorCanAccessCountry(req.adminAccount, seller.countryId)) return countryDeniedResponse(res);
        res.json({ success: true, seller });
    });

    // ==================================================
    // 3. SUSPEND / RESTORE
    // ==================================================
    function setSellerStatus(fromStatuses, toStatus, actionName) {
        return (req, res) => {
            const seller = sellers[req.params.sellerId];
            if (!seller) return res.json({ success: false, message: "Seller not found" });
            if (!actorCanAccessCountry(req.adminAccount, seller.countryId)) return countryDeniedResponse(res);
            if (!fromStatuses.includes(seller.status) && !isOwner(req.adminAccount)) {
                return res.json({ success: false, message: `This action is only allowed from '${fromStatuses.join("/")}' status (current: ${seller.status})` });
            }
            const before = Object.assign({}, seller);
            seller.status = toStatus;
            seller.updatedAt = new Date().toISOString();
            if (toStatus === "suspended") {
                seller.suspendedBy = actorTag(req);
                seller.suspendReason = (req.body.reason || req.body.note || "").trim() || null;
            } else if (toStatus === "active") {
                seller.restoredBy = actorTag(req);
                seller.restoreNote = (req.body.note || "").trim() || null;
            }
            saveSellers();
            rbac.logAction({
                admin: req.adminAccount, action: "diamond-seller-" + actionName, module: "diamond-seller",
                targetType: "diamond-seller", targetId: seller.sellerId,
                before, after: seller, ip: req.ip, userAgent: reqUserAgent(req)
            });
            notifySeller(seller, actionName);
            res.json({ success: true, seller });
        };
    }
    app.post("/api/admin/diamond-seller/sellers/:sellerId/suspend", requireAdmin, requirePermission("diamond-seller:suspend"), setSellerStatus(["active"], "suspended", "suspend"));
    app.post("/api/admin/diamond-seller/sellers/:sellerId/restore", requireAdmin, requirePermission("diamond-seller:suspend"), setSellerStatus(["suspended"], "active", "restore"));

    // ==================================================
    // 4. COMMISSION SETTINGS — rate change (kept separate from
    //    suspend/restore: this is a financial term, gated at the
    //    approve tier like everything else that moves money).
    // ==================================================
    app.post("/api/admin/diamond-seller/sellers/:sellerId/commission", requireAdmin, requirePermission("diamond-seller:approve"), (req, res) => {
        const seller = sellers[req.params.sellerId];
        if (!seller) return res.json({ success: false, message: "Seller not found" });
        if (!actorCanAccessCountry(req.adminAccount, seller.countryId)) return countryDeniedResponse(res);
        if (req.body.rate === undefined || req.body.rate === null || req.body.rate === "") return res.json({ success: false, message: "Provide a new Commission Rate" });
        const rateNum = Number(req.body.rate);
        if (!Number.isFinite(rateNum) || rateNum < MIN_COMMISSION_RATE || rateNum > MAX_COMMISSION_RATE) {
            return res.json({ success: false, message: `Provide a Commission Rate between ${MIN_COMMISSION_RATE}-${MAX_COMMISSION_RATE}%` });
        }
        const oldRate = seller.commissionRate;
        seller.commissionRate = rateNum;
        seller.updatedAt = new Date().toISOString();
        const entry = {
            type: "rate-change", at: new Date().toISOString(), by: actorTag(req),
            oldRate, newRate: rateNum, note: (req.body.note || "").trim() || null
        };
        seller.commissionHistory.push(entry);
        saveSellers();
        rbac.logAction({
            admin: req.adminAccount, action: "diamond-seller-commission-update", module: "diamond-seller",
            targetType: "diamond-seller", targetId: seller.sellerId,
            before: { commissionRate: oldRate }, after: { commissionRate: rateNum },
            ip: req.ip, userAgent: reqUserAgent(req)
        });
        notifySeller(seller, "commission-updated", { oldRate, newRate: rateNum });
        res.json({ success: true, seller });
    });

    // ==================================================
    // 5. SALE — Wallet Integration. Records an off-platform diamond sale
    //    the seller made to a buyer: credits the buyer's diamonds AND
    //    credits the seller's own coin wallet with their commission — both
    //    through the app's existing wallet primitives, nothing new
    //    invented. Only an active (non-suspended) seller can transact.
    // ==================================================
    app.post("/api/admin/diamond-seller/sellers/:sellerId/sale", requireAdmin, requirePermission("diamond-seller:submit"), (req, res) => {
        const seller = sellers[req.params.sellerId];
        if (!seller) return res.json({ success: false, message: "Seller not found" });
        if (!actorCanAccessCountry(req.adminAccount, seller.countryId)) return countryDeniedResponse(res);
        if (seller.status !== "active" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Cannot record a sale for a Suspended Seller" });
        }
        const buyerFound = findUserByUserId(req.body.buyerUserId);
        if (!buyerFound) return res.json({ success: false, message: "Provide a valid Buyer User ID" });
        const diamondAmount = Number(req.body.diamondAmount);
        if (!Number.isFinite(diamondAmount) || diamondAmount <= 0) return res.json({ success: false, message: "Provide a valid Diamond amount" });

        const sellerFound = findUserByUserId(seller.userId);
        if (!sellerFound) return res.json({ success: false, message: "The Seller's user account no longer exists" });

        const commissionCoins = Math.floor(diamondAmount * (seller.commissionRate / 100));
        const saleId = "dsale_" + Date.now().toString(36) + "_" + crypto.randomBytes(4).toString("hex");

        // Wallet mutation — buyer gets diamonds, seller gets commission coins.
        buyerFound.user.diamonds = clampDiamonds(buyerFound.user.userId, (buyerFound.user.diamonds || 0) + diamondAmount, "diamond-seller-sale");
        sellerFound.user.coins = clampCoins(sellerFound.user.userId, (sellerFound.user.coins || 0) + commissionCoins, "diamond-seller-commission");
        // LEVEL SYSTEM UPGRADE 2026-08-04: removed — a seller's commission
        // credit no longer bumps user.level (level now only changes via a
        // room gift SEND, see idLevel.js).
        saveUsers();
        logTransaction(buyerFound.user.userId, "diamonds", diamondAmount, "Diamond Seller Purchase (" + saleId + ", seller " + seller.sellerId + ")");
        if (commissionCoins > 0) logTransaction(seller.userId, "coins", commissionCoins, "Diamond Seller Commission (" + saleId + ")");
        pushWalletUpdate(buyerFound.user.userId);
        pushWalletUpdate(seller.userId);

        const entry = {
            type: "sale", saleId, at: new Date().toISOString(), recordedBy: actorTag(req),
            buyerUserId: req.body.buyerUserId, diamondAmount,
            commissionRate: seller.commissionRate, commissionCoins,
            paymentRef: (req.body.paymentRef || "").trim() || null
        };
        seller.commissionHistory.push(entry);
        seller.totalDiamondsSold = (seller.totalDiamondsSold || 0) + diamondAmount;
        seller.totalCommissionCoins = (seller.totalCommissionCoins || 0) + commissionCoins;
        seller.updatedAt = new Date().toISOString();
        saveSellers();

        rbac.logAction({
            admin: req.adminAccount, action: "diamond-seller-sale", module: "diamond-seller",
            targetType: "diamond-seller", targetId: seller.sellerId,
            after: entry, ip: req.ip, userAgent: reqUserAgent(req)
        });
        notifySeller(seller, "sale-recorded", { saleId, diamondAmount, commissionCoins });
        res.json({ success: true, seller, sale: entry });
    });

    // ==================================================
    // 6. COMMISSION HISTORY — paginated view of a seller's history
    //    (sales + rate changes together, newest first).
    // ==================================================
    app.get("/api/admin/diamond-seller/sellers/:sellerId/commission-history", requireAdmin, requirePermission("diamond-seller:view"), (req, res) => {
        const seller = sellers[req.params.sellerId];
        if (!seller) return res.json({ success: false, message: "Seller not found" });
        if (!actorCanAccessCountry(req.adminAccount, seller.countryId)) return countryDeniedResponse(res);
        let list = (seller.commissionHistory || []).slice().sort((a, b) => new Date(b.at) - new Date(a.at));
        if (req.query.type) list = list.filter((e) => e.type === req.query.type);
        const total = list.length;
        const pageSize = Math.min(Number(req.query.pageSize) || 50, 200);
        const page = Math.max(Number(req.query.page) || 1, 1);
        const start = (page - 1) * pageSize;
        res.json({ success: true, history: list.slice(start, start + pageSize), total, page, pageSize });
    });

    // ==================================================
    // 7. PUBLIC STATUS — lightweight, unauthenticated check used by the
    //    client to decide whether to show the "Seller" tag next to a
    //    user's name (profile screens only — mirrors svip's
    //    /api/svip/status/:userId pattern in server.js). Returns only a
    //    boolean, never seller PII (KYC fields, documents, commission).
    // ==================================================
    app.get("/api/diamond-seller/status/:userId", (req, res) => {
        const seller = Object.values(sellers).find((s) => s.userId === req.params.userId && s.status === "active");
        res.json({ success: true, isSeller: !!seller });
    });

    return { registration, sellers, saveSellers };
}

module.exports = { initDiamondSeller };
