// ==================================================
// PHASE 6 — VIP MODULE (item 12 of the dev sequence — last approval domain)
// ==================================================
// Grant/Approval workflow is built on the shared approvalEngine.js (same
// engine as Agency/Recharge/Withdraw/Name Effects/Frames/Gifts/Diamond
// Seller) — NO second engine written. approvalEngine.js gives this module,
// for free, on the request itself: Submit -> Review -> Approve/Reject ->
// Reopen, Approval History/Timeline, Comments, Audit Log, Country
// Isolation, Permission Checks, Owner Override, Search/Pagination/Filters
// on the request list.
//
// Everything the request workflow can't express on its own — because it
// happens to an already-approved MEMBERSHIP, not to a pending REQUEST — is
// added here as a small set of hand-written routes on a second store
// (vip_memberships.json, keyed by membershipId): Renew and (manual) Expire,
// plus a periodic auto-expiry sweep. This mirrors diamondSeller.js's
// suspend/restore section exactly (same building blocks: rbac.hasPermission
// via requirePermission, actorCanAccessCountry, rbac.logAction, isOwner
// status-guard bypass) so the security model stays identical even though
// the route isn't generated by the engine.
//
// Naming/honesty note — THIS IS NOT THE SAME THING AS THE EXISTING
// `vipLevel` / `svipLevel` FIELDS:
//   - `user.vipLevel`   — auto-computed display tier from lifetime diamonds
//                         (vipLevelFromDiamonds in server.js). Untouched.
//   - `user.svipLevel`  — SVIP wealth-level system (svip.js). Untouched.
//   - `user.vipMembership` (NEW, this file) — an admin-GRANTED, time-boxed
//                         membership tier (VIP_SILVER..VIP_ROYAL) with an
//                         expiry date, created only via this approval
//                         workflow. Independent field, independent store.
// None of the three read or write each other. This module only adds a new
// field/store; it does not modify vipLevelFromDiamonds, svip.js, or any
// existing wealth calculation.
//
// rbac.js is NOT touched by this module — `vip:view/submit/review/approve`
// and their default role assignments were already reserved in the Phase 6
// item 2 step specifically so this module wouldn't need an RBAC migration.
// Confirmed unchanged here, as instructed. There is no separate
// `vip:suspend` permission reserved, so Renew/Expire (like Diamond
// Seller's Commission Settings) are gated at the `vip:approve` tier —
// they move a real privilege window, same trust level as approving the
// grant itself.

const path = require("path");
const crypto = require("crypto");
const { createApprovalWorkflow } = require("./approvalEngine.js");

const VIP_MEMBERSHIP_TIERS = ["VIP_SILVER", "VIP_GOLD", "VIP_PLATINUM", "VIP_DIAMOND", "VIP_ROYAL"];
const MIN_DURATION_DAYS = 1;
const MAX_DURATION_DAYS = 730; // 2-year sane cap, same spirit as diamondSeller's commission-rate cap
const EXPIRY_SWEEP_INTERVAL_MS = 30 * 60 * 1000; // 30 minutes — identical cadence to svip.js's sweepAllExpiries

function clampDays(n) {
    const v = Math.floor(Number(n));
    if (!Number.isFinite(v)) return null;
    return Math.min(MAX_DURATION_DAYS, Math.max(MIN_DURATION_DAYS, v));
}

function initVipApproval(deps) {
    const {
        app, DATA_FOLDER, safeRead, safeWrite,
        findUserByUserId, saveUsers, syncProfileToRoom,
        io, socketsByUserId, emitToUser,
        rbac, requireAdmin, requirePermission,
        actorCanAccessCountry, countryDeniedResponse, reqUserAgent
    } = deps;

    const engineDeps = { app, DATA_FOLDER, safeRead, safeWrite, rbac, requireAdmin, requirePermission, actorCanAccessCountry, countryDeniedResponse, reqUserAgent };

    function isOwner(actor) { return actor && actor.role === rbac.ROLES.OWNER; }
    function actorTag(req) { return { id: req.adminAccount.id, username: req.adminAccount.username }; }

    // GAP #1 — cross-instance-safe via emitToUser()
    function notifyUser(userId, event, extra) {
        emitToUser(userId, "vip-notification", Object.assign({ event }, extra || {}));
    }

    function syncUserProfile(userId) {
        if (typeof syncProfileToRoom === "function") { try { syncProfileToRoom(userId); } catch (_) { /* room sync is best-effort */ } }
    }

    // --------------------------------------------------
    // Membership registry — separate from the request store the engine
    // manages. A request becoming "approved" is what CREATES a row here.
    // --------------------------------------------------
    const MEMBERSHIPS_FILE = path.join(DATA_FOLDER, "vip_memberships.json");
    let memberships = safeRead(MEMBERSHIPS_FILE, {});
    function saveMemberships() { safeWrite(MEMBERSHIPS_FILE, memberships); }

    function pushMembershipHistory(m, entry) {
        if (!Array.isArray(m.history)) m.history = [];
        m.history.push(Object.assign({ at: new Date().toISOString() }, entry));
    }

    function applyToUser(m) {
        const found = findUserByUserId(m.userId);
        if (!found) return;
        found.user.vipMembership = {
            membershipId: m.membershipId,
            tier: m.tier,
            active: m.status === "active",
            expireAt: m.expireAt
        };
        saveUsers();
        syncUserProfile(m.userId);
    }

    // ==================================================
    // 1. GRANT workflow (Submit -> Review -> Approve/Reject -> Reopen),
    //    fully generated by approvalEngine.js. Scoped by the TARGET USER's
    //    country (not the submitting admin's) — same convention as
    //    Recharge/Withdraw/Name Effects — since this action changes that
    //    user's profile.
    // ==================================================
    const grant = createApprovalWorkflow({
        deps: engineDeps,
        domain: "vip",
        fileName: "vip_requests.json",
        basePath: "/api/admin/vip/requests",
        idPrefix: "vpq_",
        permissions: { view: "vip:view", submit: "vip:submit", review: "vip:review", approve: "vip:approve" },
        extraSearchFields: ["tier", "targetUserName"],
        validateSubmit(body) {
            const found = findUserByUserId(body.targetUserId);
            if (!found) return { ok: false, message: "Provide a valid Target User ID (must be an existing user)" };
            if (found.user.vipMembership && found.user.vipMembership.active) {
                return { ok: false, message: "This user already has an Active VIP Membership (Expire/Renew it first)" };
            }

            const tier = VIP_MEMBERSHIP_TIERS.includes(body.tier) ? body.tier : null;
            if (!tier) return { ok: false, message: "Select a valid VIP Tier (" + VIP_MEMBERSHIP_TIERS.join("/") + ")" };

            const durationDays = clampDays(body.durationDays);
            if (!durationDays) return { ok: false, message: `Duration ${MIN_DURATION_DAYS}-${MAX_DURATION_DAYS} days` };

            return {
                ok: true,
                userId: body.targetUserId,
                countryId: found.user.countryId || "OTHERS",
                data: { domain: "vip", tier, durationDays, targetUserName: found.user.name || null }
            };
        },
        onApprove(record, req) {
            const found = findUserByUserId(record.userId);
            if (!found) return { ok: false, message: "User no longer exists" };
            if (found.user.vipMembership && found.user.vipMembership.active) {
                return { ok: false, message: "This user already has an Active VIP Membership" };
            }

            const membershipId = "vpm_" + Date.now().toString(36) + "_" + crypto.randomBytes(4).toString("hex");
            const startAt = new Date().toISOString();
            const expireAt = new Date(Date.now() + record.durationDays * 24 * 60 * 60 * 1000).toISOString();
            const membership = {
                membershipId,
                userId: record.userId,
                countryId: record.countryId,
                tier: record.tier,
                status: "active",
                startAt,
                expireAt,
                initialDurationDays: record.durationDays,
                viaRequestId: record.requestId,
                grantedBy: actorTag(req),
                history: [],
                createdAt: startAt,
                updatedAt: startAt
            };
            pushMembershipHistory(membership, { type: "grant", by: actorTag(req), tier: record.tier, days: record.durationDays, expireAt });
            memberships[membershipId] = membership;
            saveMemberships();
            applyToUser(membership);

            notifyUser(record.userId, "granted", { membershipId, tier: record.tier, expireAt });
            return { ok: true, extra: { membershipId } };
        },
        onNotify(record, event) {
            // GAP #1 — cross-instance-safe via emitToUser()
            emitToUser(record.userId, "approval-notification", {
                domain: "vip", requestId: record.requestId, status: record.status, event,
                note: record.decisionNote || record.reviewNote || null
            });
        }
    });

    // ==================================================
    // 2. MEMBERSHIP LIST — search / filter / pagination (on the membership
    //    registry, not the request queue).
    // ==================================================
    app.get("/api/admin/vip/memberships", requireAdmin, requirePermission("vip:view"), (req, res) => {
        let list = Object.values(memberships).filter((m) => actorCanAccessCountry(req.adminAccount, m.countryId));
        if (req.query.status) list = list.filter((m) => m.status === req.query.status);
        if (req.query.tier) list = list.filter((m) => m.tier === req.query.tier);
        if (req.query.countryId) list = list.filter((m) => m.countryId === req.query.countryId);
        if (req.query.userId) list = list.filter((m) => m.userId === req.query.userId);
        if (req.query.q) {
            const q = String(req.query.q).toLowerCase();
            list = list.filter((m) => [m.membershipId, m.userId, m.tier].some((f) => String(f || "").toLowerCase().includes(q)));
        }
        list = list.slice().sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
        const total = list.length;
        const pageSize = Math.min(Number(req.query.pageSize) || 50, 200);
        const page = Math.max(Number(req.query.page) || 1, 1);
        const start = (page - 1) * pageSize;
        res.json({ success: true, memberships: list.slice(start, start + pageSize), total, page, pageSize });
    });

    app.get("/api/admin/vip/memberships/:membershipId", requireAdmin, requirePermission("vip:view"), (req, res) => {
        const m = memberships[req.params.membershipId];
        if (!m) return res.json({ success: false, message: "Membership not found" });
        if (!actorCanAccessCountry(req.adminAccount, m.countryId)) return countryDeniedResponse(res);
        res.json({ success: true, membership: m });
    });

    // ==================================================
    // 3. RENEW — extends (or reactivates) a membership. Non-owner: only
    //    from "active" (renew before it lapses). Owner: any status,
    //    including "expired" — same override convention as
    //    diamondSeller.js's setSellerStatus.
    // ==================================================
    app.post("/api/admin/vip/memberships/:membershipId/renew", requireAdmin, requirePermission("vip:approve"), (req, res) => {
        const m = memberships[req.params.membershipId];
        if (!m) return res.json({ success: false, message: "Membership not found" });
        if (!actorCanAccessCountry(req.adminAccount, m.countryId)) return countryDeniedResponse(res);
        if (m.status !== "active" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Only an 'active' membership can be renewed (current status: " + m.status + ")" });
        }
        const days = clampDays(req.body.days);
        if (!days) return res.json({ success: false, message: `Renewal Duration ${MIN_DURATION_DAYS}-${MAX_DURATION_DAYS} days` });

        const before = Object.assign({}, m);
        // Extend from the later of "now" or the current expiry, so renewing
        // early adds on top of remaining time instead of discarding it.
        const base = Math.max(Date.now(), new Date(m.expireAt).getTime() || 0);
        m.expireAt = new Date(base + days * 24 * 60 * 60 * 1000).toISOString();
        m.status = "active";
        m.updatedAt = new Date().toISOString();
        pushMembershipHistory(m, { type: "renew", by: actorTag(req), days, expireAt: m.expireAt, note: (req.body.note || "").trim() || null });
        saveMemberships();
        applyToUser(m);

        rbac.logAction({
            admin: req.adminAccount, action: "vip-renew", module: "vip",
            targetType: "vip-membership", targetId: m.membershipId,
            before, after: m, ip: req.ip, userAgent: reqUserAgent(req)
        });
        notifyUser(m.userId, "renewed", { membershipId: m.membershipId, expireAt: m.expireAt });
        res.json({ success: true, membership: m });
    });

    // ==================================================
    // 4. EXPIRE — manual force-expire. Non-owner: only from "active".
    //    Owner: any status.
    // ==================================================
    app.post("/api/admin/vip/memberships/:membershipId/expire", requireAdmin, requirePermission("vip:approve"), (req, res) => {
        const m = memberships[req.params.membershipId];
        if (!m) return res.json({ success: false, message: "Membership not found" });
        if (!actorCanAccessCountry(req.adminAccount, m.countryId)) return countryDeniedResponse(res);
        if (m.status !== "active" && !isOwner(req.adminAccount)) {
            return res.json({ success: false, message: "Only an 'active' membership can be expired (current status: " + m.status + ")" });
        }
        const before = Object.assign({}, m);
        m.status = "expired";
        m.updatedAt = new Date().toISOString();
        pushMembershipHistory(m, { type: "expire", reason: "manual", by: actorTag(req), note: (req.body.note || req.body.reason || "").trim() || null });
        saveMemberships();
        applyToUser(m);

        rbac.logAction({
            admin: req.adminAccount, action: "vip-expire", module: "vip",
            targetType: "vip-membership", targetId: m.membershipId,
            before, after: m, ip: req.ip, userAgent: reqUserAgent(req)
        });
        notifyUser(m.userId, "expired", { membershipId: m.membershipId, reason: "manual" });
        res.json({ success: true, membership: m });
    });

    // ==================================================
    // 5. HISTORY / TIMELINE — paginated view of a membership's history
    //    (grant + renew + expire entries together, newest first).
    // ==================================================
    app.get("/api/admin/vip/memberships/:membershipId/history", requireAdmin, requirePermission("vip:view"), (req, res) => {
        const m = memberships[req.params.membershipId];
        if (!m) return res.json({ success: false, message: "Membership not found" });
        if (!actorCanAccessCountry(req.adminAccount, m.countryId)) return countryDeniedResponse(res);
        let list = (m.history || []).slice().sort((a, b) => new Date(b.at) - new Date(a.at));
        if (req.query.type) list = list.filter((e) => e.type === req.query.type);
        const total = list.length;
        const pageSize = Math.min(Number(req.query.pageSize) || 50, 200);
        const page = Math.max(Number(req.query.page) || 1, 1);
        const start = (page - 1) * pageSize;
        res.json({ success: true, history: list.slice(start, start + pageSize), total, page, pageSize });
    });

    // ==================================================
    // 6. AUTO-EXPIRY SWEEP — covers memberships whose owner never triggers
    //    a manual /expire and whose user may be offline. Identical cadence
    //    (30 min) and shape to svip.js's sweepAllExpiries, logged as a
    //    "system" audit entry (admin: null — rbac.logAction already
    //    supports this, see logAction's adminUsername: admin ? ... :
    //    "system").
    // ==================================================
    function sweepExpiredMemberships() {
        const now = Date.now();
        Object.values(memberships).forEach((m) => {
            if (m.status !== "active") return;
            if (new Date(m.expireAt).getTime() > now) return;
            const before = Object.assign({}, m);
            m.status = "expired";
            m.updatedAt = new Date().toISOString();
            pushMembershipHistory(m, { type: "expire", reason: "auto", by: null });
            applyToUser(m);
            rbac.logAction({
                admin: null, action: "vip-expire", module: "vip",
                targetType: "vip-membership", targetId: m.membershipId,
                before, after: m, meta: { reason: "auto-sweep" }
            });
            notifyUser(m.userId, "expired", { membershipId: m.membershipId, reason: "auto" });
        });
        saveMemberships();
    }
    setInterval(sweepExpiredMemberships, EXPIRY_SWEEP_INTERVAL_MS);

    return { grant, memberships, saveMemberships, VIP_MEMBERSHIP_TIERS };
}

module.exports = { initVipApproval, VIP_MEMBERSHIP_TIERS };
